### PR TITLE
Review suggestions for `feature_jg`

### PR DESCRIPTION
**Pull request by fneum**
review for https://github.com/PyPSA/pypsa-ariadne/pull/6

@JulianGeis looks very good! I have revised the code to:

- use a few Python tricks to make the code cleaner / shorter (have a look at the diff)
- reuse more of the functions from `cluster_gas_network` from PyPSA-Eur
- make mock_snakemake work in pypsa-ariadne

My questions:

1. The build year of the hydrogen pipelines is not considered, right? In `prepare_sector_network`, one could add a line

```py
custom_pipes.query("build_year <= @investment_year", inplace=True)
```

after reading the file so that the minimum capacities and routes depend on the planning horizon.

2. Is the clipping to a minimum pressure of 30 bar and a minimum build year 2030 necessary? Should the latter maybe be a config option?

3. Does it make a difference if you set the acceptable length ratio to a higher value?

4. Did it make a difference if you applied the line segmentation approach?

### CODE REVIEW

**Review by JulianGeis — APPROVED** [review]
Thanks for the review. It is definitely cleaner now.

**Comment by JulianGeis** [comment]
Answering your questions:
1. Right, the build year is not yet considered. I also did not put too much effort in extracting it properly. However with your suggested method it is done properly. If one implements 

'''

**Comment by JulianGeis** [comment]
Answering your questions:
1. Right, the build year is not yet considered. I also did not put too much effort in extracting it properly. However with your suggested method it is done properly. If one implements the selection by date as you suggest, the clipping should not be done. Actually, I did not really do a clipping for the year as the clipping year was set to 2020. I just wanted to exclude unrealistic values. 

2. Clipping the minimum pressure to 30 bar is not really necessary. There are only 9 values below 30 anyways, which are all 25. Clipping the build year is also not necessary. 

3. The current value of 2 excludes these 8 pipes:
image
Most of them seem ok, if you look at the names of the start and end, but the length is really of. It would not change the network massively if they were included. However, I thought it would be more conservative to not include them. But especially the line in Bavaria is making sense and is an important one. So I would be okay with just keeping them.

4. The line segmentation approach did lead to different results in terms of pipelines. For the 22 clusters these were the two results:

Without line segmentation:
image

With line segmentation:
image

This makes sense, as the segmentation creates more start / end points which may lie within a region that was not included before as the pipe went directly trough. This is for example the case for CZ. It can also happen that some pipes or connections are no more present as it is the case for Germany. This happens if the segmentation splits pipes, so that they connect A and B via C and not directly again. The capacity is still there only going trough another location. 





'''
custom_pipes.query("build_year <= @investment_year", inplace=True)
'''

**Comment by fneum** [comment]
All good!

For 3., I would also be ok with keeping them.

For 4., I'm in favour of apply the line segmentation by default.

**Pull request merged**
