### PR TITLE
Use environment secrets

### PR DESCRIPTION
**Pull request by lindnemi**
Like @fneum suggested, Snakemake environment variables can be used to avoid accidental commits of private usernames and passwords to the repository. Since we are working more and more with the IIASA Database it became tedious to keep adding and removing the login details from the config. With this PR you will need to add the Username and password only once to you `.bashrc`

Step 1: 

`vim ~/.bashrc`

Step 2:

at the end of the file add

```
export IIASA_USERNAME='usr'
export IIASA_PASSWORD='pwd'
```
(Insert correct usr and pwd and don't forget the quotation marks)

Step 3:

(Maybe) restart your vscode / terminal session

### CODE REVIEW

**Comment by lindnemi** [comment]
sorry about the two minor commits in the branch, they accidentally snug in, they won't hurt, but i can remove them if you want a cleaner PR

**Comment by fneum** [comment]
Looks good! Could you add these instructions to the README?

**Comment by lindnemi** [comment]
Done

**Comment by fneum** [comment]
Great, is it intended that the PyPSA-Eur submodule also moves forward?

**Comment by lindnemi** [comment]
nope, good catch

**Comment by lindnemi** [comment]
not working completley with vscode yet...

**Comment by fneum** [comment]
Works for me. Did you also source in vscode?

**Pull request merged**
