### PR TITLE
Add max capacity limits for renewable energies in Germany

### PR DESCRIPTION
**Pull request by toniseibold**
Since our results showed too much renewable energies in 2020 and 2025, a maximum constraint is introduced.
`config["limits_capacity_max"]` follows the same logic as `config["limits_capacity_min"].
Be aware that defining both upper and lower limits for renewables is possible but might lead to numerical issues.

### CODE REVIEW

**Comment by lindnemi** [comment]
- The way the capacity limits are implement at the moment, they only check if the carrier starts with `solar`. Hence, they would include `solar thermal` at the moment, which is probably not correct.
- @JulianGeis i can confirm 0 offshore wind in 2020. introducing the capacity min again could be a solution, but then we would basically introduce an equality constraint. i am not sure if this might lead to numerical errors, but we could try
- @toniseibold i think the constraint might have the wrong orientation and requires a `<=` instead of `>=` in line 80. It seems that at the moment the specified capacity_limits in 2020 are not applied in the model

**Comment by lindnemi** [comment]
Existing solar capacities for the 2020 model are 81 GW, onshore wind 61 GW. Both are bigger than historical values. The reason is that the generator solar-2019 contains all capacities added in 2019 and later. Since our input data already contains solar added after 2020, we get excess capacities

**Comment by lindnemi** [comment]
we could throw out the extra capacities, but then they would be missing in later years (except that they probably get build by the model anyway)

**Comment by lindnemi** [comment]
My suggestion: Keep extra capacity, allow no further extension, issue a warning. This will imply that we have too much RES generation in 2020 and can not exactly validate against data for 2020.

**Comment by lindnemi** [comment]
@toniseibold changed the logic for Maximum limits slightly, please take a look

**Comment by toniseibold** [comment]
Logic looks good. Could add `"residential rural solar thermal", "services rural solar thermal", "residential urban decentral solar thermal", "services urban decentral solar thermal", "urban central solar thermal"` to the `forbidden` variable just to be on the safe side.

**Pull request merged**
