### PR TITLE
Preparation for public model Pypsa-DE

### PR DESCRIPTION
**Pull request by lindnemi**
This PR prepares the renaming and publication of the repository as PyPSA-DE.

- [x] A new configfile `config.public.yaml` is created, which let's the any user connect to the public version of the Ariadne 1 database

- [x] The computation of the non-co2 emissions from REMIND has been adjusted to be compatible with ariadne1 as well as ariadne 2 (internal). 

- [x] Documentation improvements

Adressing #69, #56.

### CODE REVIEW

**Comment by lindnemi** [comment]
When testing this we have to make sure that it works both with and without `--configfile=config.public.yaml`

**Comment by JulianGeis** [comment]
image
 
replace with AFOLU?

**Comment by lindnemi** [comment]
Should be fixed, please try again

**Comment by JulianGeis** [comment]
I did run the workflow with and without `--configfile=config.public.yaml`. Both workflows did run for the default models (public: 8Gt_Bal_v3; ariadne: KN2045_Bal_v4).

## Results look fine:
 **public: 8Gt_Bal_v3**
image


**ariadne: KN2045_Bal_v4**
image

However some plots for the public model are empty: e.g. final energy
image

Is this intended?

**Comment by lindnemi** [comment]
yes , the empty plots are intended. the public database is lacking some variables

**Pull request merged**
